# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.14

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake3

# The command to remove a file.
RM = /usr/bin/cmake3 -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/tobias/codes/MAD-X

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/tobias/codes/MAD-X

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake3 -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake3 -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake3 -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake3 -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake3 -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake3 -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Files\" \"Libraries\" \"Runtime\" \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake3 -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake3 -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target package_source
package_source:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Run CPack packaging tool for source..."
	/usr/bin/cpack3 --config ./CPackSourceConfig.cmake /home/tobias/codes/MAD-X/CPackSourceConfig.cmake
.PHONY : package_source

# Special rule for the target package_source
package_source/fast: package_source

.PHONY : package_source/fast

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running tests..."
	/usr/bin/ctest3 --force-new-ctest-process $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test

.PHONY : test/fast

# Special rule for the target package
package: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Run CPack packaging tool..."
	/usr/bin/cpack3 --config ./CPackConfig.cmake
.PHONY : package

# Special rule for the target package
package/fast: package

.PHONY : package/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/tobias/codes/MAD-X/CMakeFiles /home/tobias/codes/MAD-X/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/tobias/codes/MAD-X/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named check

# Build rule for target.
check: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 check
.PHONY : check

# fast build rule for target.
check/fast:
	$(MAKE) -f CMakeFiles/check.dir/build.make CMakeFiles/check.dir/build
.PHONY : check/fast

#=============================================================================
# Target rules for targets named gcmt-dll

# Build rule for target.
gcmt-dll: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 gcmt-dll
.PHONY : gcmt-dll

# fast build rule for target.
gcmt-dll/fast:
	$(MAKE) -f libs/gc/gc-8.0.2/CMakeFiles/gcmt-dll.dir/build.make libs/gc/gc-8.0.2/CMakeFiles/gcmt-dll.dir/build
.PHONY : gcmt-dll/fast

#=============================================================================
# Target rules for targets named gc-lib

# Build rule for target.
gc-lib: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 gc-lib
.PHONY : gc-lib

# fast build rule for target.
gc-lib/fast:
	$(MAKE) -f libs/gc/gc-8.0.2/CMakeFiles/gc-lib.dir/build.make libs/gc/gc-8.0.2/CMakeFiles/gc-lib.dir/build
.PHONY : gc-lib/fast

#=============================================================================
# Target rules for targets named ContinuousSubmit

# Build rule for target.
ContinuousSubmit: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ContinuousSubmit
.PHONY : ContinuousSubmit

# fast build rule for target.
ContinuousSubmit/fast:
	$(MAKE) -f libs/gc/gc-8.0.2/CMakeFiles/ContinuousSubmit.dir/build.make libs/gc/gc-8.0.2/CMakeFiles/ContinuousSubmit.dir/build
.PHONY : ContinuousSubmit/fast

#=============================================================================
# Target rules for targets named ContinuousCoverage

# Build rule for target.
ContinuousCoverage: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ContinuousCoverage
.PHONY : ContinuousCoverage

# fast build rule for target.
ContinuousCoverage/fast:
	$(MAKE) -f libs/gc/gc-8.0.2/CMakeFiles/ContinuousCoverage.dir/build.make libs/gc/gc-8.0.2/CMakeFiles/ContinuousCoverage.dir/build
.PHONY : ContinuousCoverage/fast

#=============================================================================
# Target rules for targets named ContinuousTest

# Build rule for target.
ContinuousTest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ContinuousTest
.PHONY : ContinuousTest

# fast build rule for target.
ContinuousTest/fast:
	$(MAKE) -f libs/gc/gc-8.0.2/CMakeFiles/ContinuousTest.dir/build.make libs/gc/gc-8.0.2/CMakeFiles/ContinuousTest.dir/build
.PHONY : ContinuousTest/fast

#=============================================================================
# Target rules for targets named ContinuousBuild

# Build rule for target.
ContinuousBuild: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ContinuousBuild
.PHONY : ContinuousBuild

# fast build rule for target.
ContinuousBuild/fast:
	$(MAKE) -f libs/gc/gc-8.0.2/CMakeFiles/ContinuousBuild.dir/build.make libs/gc/gc-8.0.2/CMakeFiles/ContinuousBuild.dir/build
.PHONY : ContinuousBuild/fast

#=============================================================================
# Target rules for targets named ContinuousMemCheck

# Build rule for target.
ContinuousMemCheck: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ContinuousMemCheck
.PHONY : ContinuousMemCheck

# fast build rule for target.
ContinuousMemCheck/fast:
	$(MAKE) -f libs/gc/gc-8.0.2/CMakeFiles/ContinuousMemCheck.dir/build.make libs/gc/gc-8.0.2/CMakeFiles/ContinuousMemCheck.dir/build
.PHONY : ContinuousMemCheck/fast

#=============================================================================
# Target rules for targets named Nightly

# Build rule for target.
Nightly: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Nightly
.PHONY : Nightly

# fast build rule for target.
Nightly/fast:
	$(MAKE) -f libs/gc/gc-8.0.2/CMakeFiles/Nightly.dir/build.make libs/gc/gc-8.0.2/CMakeFiles/Nightly.dir/build
.PHONY : Nightly/fast

#=============================================================================
# Target rules for targets named NightlyTest

# Build rule for target.
NightlyTest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 NightlyTest
.PHONY : NightlyTest

# fast build rule for target.
NightlyTest/fast:
	$(MAKE) -f libs/gc/gc-8.0.2/CMakeFiles/NightlyTest.dir/build.make libs/gc/gc-8.0.2/CMakeFiles/NightlyTest.dir/build
.PHONY : NightlyTest/fast

#=============================================================================
# Target rules for targets named NightlyUpdate

# Build rule for target.
NightlyUpdate: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 NightlyUpdate
.PHONY : NightlyUpdate

# fast build rule for target.
NightlyUpdate/fast:
	$(MAKE) -f libs/gc/gc-8.0.2/CMakeFiles/NightlyUpdate.dir/build.make libs/gc/gc-8.0.2/CMakeFiles/NightlyUpdate.dir/build
.PHONY : NightlyUpdate/fast

#=============================================================================
# Target rules for targets named NightlyBuild

# Build rule for target.
NightlyBuild: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 NightlyBuild
.PHONY : NightlyBuild

# fast build rule for target.
NightlyBuild/fast:
	$(MAKE) -f libs/gc/gc-8.0.2/CMakeFiles/NightlyBuild.dir/build.make libs/gc/gc-8.0.2/CMakeFiles/NightlyBuild.dir/build
.PHONY : NightlyBuild/fast

#=============================================================================
# Target rules for targets named Continuous

# Build rule for target.
Continuous: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Continuous
.PHONY : Continuous

# fast build rule for target.
Continuous/fast:
	$(MAKE) -f libs/gc/gc-8.0.2/CMakeFiles/Continuous.dir/build.make libs/gc/gc-8.0.2/CMakeFiles/Continuous.dir/build
.PHONY : Continuous/fast

#=============================================================================
# Target rules for targets named gcmt-lib

# Build rule for target.
gcmt-lib: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 gcmt-lib
.PHONY : gcmt-lib

# fast build rule for target.
gcmt-lib/fast:
	$(MAKE) -f libs/gc/gc-8.0.2/CMakeFiles/gcmt-lib.dir/build.make libs/gc/gc-8.0.2/CMakeFiles/gcmt-lib.dir/build
.PHONY : gcmt-lib/fast

#=============================================================================
# Target rules for targets named NightlyStart

# Build rule for target.
NightlyStart: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 NightlyStart
.PHONY : NightlyStart

# fast build rule for target.
NightlyStart/fast:
	$(MAKE) -f libs/gc/gc-8.0.2/CMakeFiles/NightlyStart.dir/build.make libs/gc/gc-8.0.2/CMakeFiles/NightlyStart.dir/build
.PHONY : NightlyStart/fast

#=============================================================================
# Target rules for targets named NightlyMemoryCheck

# Build rule for target.
NightlyMemoryCheck: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 NightlyMemoryCheck
.PHONY : NightlyMemoryCheck

# fast build rule for target.
NightlyMemoryCheck/fast:
	$(MAKE) -f libs/gc/gc-8.0.2/CMakeFiles/NightlyMemoryCheck.dir/build.make libs/gc/gc-8.0.2/CMakeFiles/NightlyMemoryCheck.dir/build
.PHONY : NightlyMemoryCheck/fast

#=============================================================================
# Target rules for targets named NightlyMemCheck

# Build rule for target.
NightlyMemCheck: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 NightlyMemCheck
.PHONY : NightlyMemCheck

# fast build rule for target.
NightlyMemCheck/fast:
	$(MAKE) -f libs/gc/gc-8.0.2/CMakeFiles/NightlyMemCheck.dir/build.make libs/gc/gc-8.0.2/CMakeFiles/NightlyMemCheck.dir/build
.PHONY : NightlyMemCheck/fast

#=============================================================================
# Target rules for targets named ExperimentalStart

# Build rule for target.
ExperimentalStart: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ExperimentalStart
.PHONY : ExperimentalStart

# fast build rule for target.
ExperimentalStart/fast:
	$(MAKE) -f libs/gc/gc-8.0.2/CMakeFiles/ExperimentalStart.dir/build.make libs/gc/gc-8.0.2/CMakeFiles/ExperimentalStart.dir/build
.PHONY : ExperimentalStart/fast

#=============================================================================
# Target rules for targets named ContinuousConfigure

# Build rule for target.
ContinuousConfigure: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ContinuousConfigure
.PHONY : ContinuousConfigure

# fast build rule for target.
ContinuousConfigure/fast:
	$(MAKE) -f libs/gc/gc-8.0.2/CMakeFiles/ContinuousConfigure.dir/build.make libs/gc/gc-8.0.2/CMakeFiles/ContinuousConfigure.dir/build
.PHONY : ContinuousConfigure/fast

#=============================================================================
# Target rules for targets named NightlyCoverage

# Build rule for target.
NightlyCoverage: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 NightlyCoverage
.PHONY : NightlyCoverage

# fast build rule for target.
NightlyCoverage/fast:
	$(MAKE) -f libs/gc/gc-8.0.2/CMakeFiles/NightlyCoverage.dir/build.make libs/gc/gc-8.0.2/CMakeFiles/NightlyCoverage.dir/build
.PHONY : NightlyCoverage/fast

#=============================================================================
# Target rules for targets named ExperimentalUpdate

# Build rule for target.
ExperimentalUpdate: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ExperimentalUpdate
.PHONY : ExperimentalUpdate

# fast build rule for target.
ExperimentalUpdate/fast:
	$(MAKE) -f libs/gc/gc-8.0.2/CMakeFiles/ExperimentalUpdate.dir/build.make libs/gc/gc-8.0.2/CMakeFiles/ExperimentalUpdate.dir/build
.PHONY : ExperimentalUpdate/fast

#=============================================================================
# Target rules for targets named ExperimentalConfigure

# Build rule for target.
ExperimentalConfigure: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ExperimentalConfigure
.PHONY : ExperimentalConfigure

# fast build rule for target.
ExperimentalConfigure/fast:
	$(MAKE) -f libs/gc/gc-8.0.2/CMakeFiles/ExperimentalConfigure.dir/build.make libs/gc/gc-8.0.2/CMakeFiles/ExperimentalConfigure.dir/build
.PHONY : ExperimentalConfigure/fast

#=============================================================================
# Target rules for targets named ExperimentalCoverage

# Build rule for target.
ExperimentalCoverage: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ExperimentalCoverage
.PHONY : ExperimentalCoverage

# fast build rule for target.
ExperimentalCoverage/fast:
	$(MAKE) -f libs/gc/gc-8.0.2/CMakeFiles/ExperimentalCoverage.dir/build.make libs/gc/gc-8.0.2/CMakeFiles/ExperimentalCoverage.dir/build
.PHONY : ExperimentalCoverage/fast

#=============================================================================
# Target rules for targets named ExperimentalBuild

# Build rule for target.
ExperimentalBuild: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ExperimentalBuild
.PHONY : ExperimentalBuild

# fast build rule for target.
ExperimentalBuild/fast:
	$(MAKE) -f libs/gc/gc-8.0.2/CMakeFiles/ExperimentalBuild.dir/build.make libs/gc/gc-8.0.2/CMakeFiles/ExperimentalBuild.dir/build
.PHONY : ExperimentalBuild/fast

#=============================================================================
# Target rules for targets named NightlyConfigure

# Build rule for target.
NightlyConfigure: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 NightlyConfigure
.PHONY : NightlyConfigure

# fast build rule for target.
NightlyConfigure/fast:
	$(MAKE) -f libs/gc/gc-8.0.2/CMakeFiles/NightlyConfigure.dir/build.make libs/gc/gc-8.0.2/CMakeFiles/NightlyConfigure.dir/build
.PHONY : NightlyConfigure/fast

#=============================================================================
# Target rules for targets named ExperimentalTest

# Build rule for target.
ExperimentalTest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ExperimentalTest
.PHONY : ExperimentalTest

# fast build rule for target.
ExperimentalTest/fast:
	$(MAKE) -f libs/gc/gc-8.0.2/CMakeFiles/ExperimentalTest.dir/build.make libs/gc/gc-8.0.2/CMakeFiles/ExperimentalTest.dir/build
.PHONY : ExperimentalTest/fast

#=============================================================================
# Target rules for targets named ExperimentalMemCheck

# Build rule for target.
ExperimentalMemCheck: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ExperimentalMemCheck
.PHONY : ExperimentalMemCheck

# fast build rule for target.
ExperimentalMemCheck/fast:
	$(MAKE) -f libs/gc/gc-8.0.2/CMakeFiles/ExperimentalMemCheck.dir/build.make libs/gc/gc-8.0.2/CMakeFiles/ExperimentalMemCheck.dir/build
.PHONY : ExperimentalMemCheck/fast

#=============================================================================
# Target rules for targets named Experimental

# Build rule for target.
Experimental: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Experimental
.PHONY : Experimental

# fast build rule for target.
Experimental/fast:
	$(MAKE) -f libs/gc/gc-8.0.2/CMakeFiles/Experimental.dir/build.make libs/gc/gc-8.0.2/CMakeFiles/Experimental.dir/build
.PHONY : Experimental/fast

#=============================================================================
# Target rules for targets named NightlySubmit

# Build rule for target.
NightlySubmit: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 NightlySubmit
.PHONY : NightlySubmit

# fast build rule for target.
NightlySubmit/fast:
	$(MAKE) -f libs/gc/gc-8.0.2/CMakeFiles/NightlySubmit.dir/build.make libs/gc/gc-8.0.2/CMakeFiles/NightlySubmit.dir/build
.PHONY : NightlySubmit/fast

#=============================================================================
# Target rules for targets named ExperimentalSubmit

# Build rule for target.
ExperimentalSubmit: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ExperimentalSubmit
.PHONY : ExperimentalSubmit

# fast build rule for target.
ExperimentalSubmit/fast:
	$(MAKE) -f libs/gc/gc-8.0.2/CMakeFiles/ExperimentalSubmit.dir/build.make libs/gc/gc-8.0.2/CMakeFiles/ExperimentalSubmit.dir/build
.PHONY : ExperimentalSubmit/fast

#=============================================================================
# Target rules for targets named ContinuousStart

# Build rule for target.
ContinuousStart: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ContinuousStart
.PHONY : ContinuousStart

# fast build rule for target.
ContinuousStart/fast:
	$(MAKE) -f libs/gc/gc-8.0.2/CMakeFiles/ContinuousStart.dir/build.make libs/gc/gc-8.0.2/CMakeFiles/ContinuousStart.dir/build
.PHONY : ContinuousStart/fast

#=============================================================================
# Target rules for targets named ContinuousUpdate

# Build rule for target.
ContinuousUpdate: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ContinuousUpdate
.PHONY : ContinuousUpdate

# fast build rule for target.
ContinuousUpdate/fast:
	$(MAKE) -f libs/gc/gc-8.0.2/CMakeFiles/ContinuousUpdate.dir/build.make libs/gc/gc-8.0.2/CMakeFiles/ContinuousUpdate.dir/build
.PHONY : ContinuousUpdate/fast

#=============================================================================
# Target rules for targets named hugetest

# Build rule for target.
hugetest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 hugetest
.PHONY : hugetest

# fast build rule for target.
hugetest/fast:
	$(MAKE) -f libs/gc/gc-8.0.2/tests/CMakeFiles/hugetest.dir/build.make libs/gc/gc-8.0.2/tests/CMakeFiles/hugetest.dir/build
.PHONY : hugetest/fast

#=============================================================================
# Target rules for targets named realloc_test

# Build rule for target.
realloc_test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 realloc_test
.PHONY : realloc_test

# fast build rule for target.
realloc_test/fast:
	$(MAKE) -f libs/gc/gc-8.0.2/tests/CMakeFiles/realloc_test.dir/build.make libs/gc/gc-8.0.2/tests/CMakeFiles/realloc_test.dir/build
.PHONY : realloc_test/fast

#=============================================================================
# Target rules for targets named leaktest

# Build rule for target.
leaktest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 leaktest
.PHONY : leaktest

# fast build rule for target.
leaktest/fast:
	$(MAKE) -f libs/gc/gc-8.0.2/tests/CMakeFiles/leaktest.dir/build.make libs/gc/gc-8.0.2/tests/CMakeFiles/leaktest.dir/build
.PHONY : leaktest/fast

#=============================================================================
# Target rules for targets named gctest

# Build rule for target.
gctest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 gctest
.PHONY : gctest

# fast build rule for target.
gctest/fast:
	$(MAKE) -f libs/gc/gc-8.0.2/tests/CMakeFiles/gctest.dir/build.make libs/gc/gc-8.0.2/tests/CMakeFiles/gctest.dir/build
.PHONY : gctest/fast

#=============================================================================
# Target rules for targets named middletest

# Build rule for target.
middletest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 middletest
.PHONY : middletest

# fast build rule for target.
middletest/fast:
	$(MAKE) -f libs/gc/gc-8.0.2/tests/CMakeFiles/middletest.dir/build.make libs/gc/gc-8.0.2/tests/CMakeFiles/middletest.dir/build
.PHONY : middletest/fast

#=============================================================================
# Target rules for targets named smashtest

# Build rule for target.
smashtest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 smashtest
.PHONY : smashtest

# fast build rule for target.
smashtest/fast:
	$(MAKE) -f libs/gc/gc-8.0.2/tests/CMakeFiles/smashtest.dir/build.make libs/gc/gc-8.0.2/tests/CMakeFiles/smashtest.dir/build
.PHONY : smashtest/fast

#=============================================================================
# Target rules for targets named DISTlib

# Build rule for target.
DISTlib: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 DISTlib
.PHONY : DISTlib

# fast build rule for target.
DISTlib/fast:
	$(MAKE) -f libs/DISTlib/source/CMakeFiles/DISTlib.dir/build.make libs/DISTlib/source/CMakeFiles/DISTlib.dir/build
.PHONY : DISTlib/fast

#=============================================================================
# Target rules for targets named ptc

# Build rule for target.
ptc: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ptc
.PHONY : ptc

# fast build rule for target.
ptc/fast:
	$(MAKE) -f libs/ptc/src/CMakeFiles/ptc.dir/build.make libs/ptc/src/CMakeFiles/ptc.dir/build
.PHONY : ptc/fast

#=============================================================================
# Target rules for targets named madx

# Build rule for target.
madx: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 madx
.PHONY : madx

# fast build rule for target.
madx/fast:
	$(MAKE) -f src/CMakeFiles/madx.dir/build.make src/CMakeFiles/madx.dir/build
.PHONY : madx/fast

#=============================================================================
# Target rules for targets named madxbin

# Build rule for target.
madxbin: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 madxbin
.PHONY : madxbin

# fast build rule for target.
madxbin/fast:
	$(MAKE) -f src/CMakeFiles/madxbin.dir/build.make src/CMakeFiles/madxbin.dir/build
.PHONY : madxbin/fast

#=============================================================================
# Target rules for targets named ndiff

# Build rule for target.
ndiff: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ndiff
.PHONY : ndiff

# fast build rule for target.
ndiff/fast:
	$(MAKE) -f tools/numdiff/CMakeFiles/ndiff.dir/build.make tools/numdiff/CMakeFiles/ndiff.dir/build
.PHONY : ndiff/fast

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... install/strip"
	@echo "... install/local"
	@echo "... install"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... package_source"
	@echo "... test"
	@echo "... package"
	@echo "... check"
	@echo "... gcmt-dll"
	@echo "... gc-lib"
	@echo "... ContinuousSubmit"
	@echo "... ContinuousCoverage"
	@echo "... ContinuousTest"
	@echo "... ContinuousBuild"
	@echo "... ContinuousMemCheck"
	@echo "... Nightly"
	@echo "... NightlyTest"
	@echo "... NightlyUpdate"
	@echo "... NightlyBuild"
	@echo "... Continuous"
	@echo "... gcmt-lib"
	@echo "... NightlyStart"
	@echo "... NightlyMemoryCheck"
	@echo "... NightlyMemCheck"
	@echo "... ExperimentalStart"
	@echo "... ContinuousConfigure"
	@echo "... NightlyCoverage"
	@echo "... ExperimentalUpdate"
	@echo "... ExperimentalConfigure"
	@echo "... ExperimentalCoverage"
	@echo "... ExperimentalBuild"
	@echo "... NightlyConfigure"
	@echo "... ExperimentalTest"
	@echo "... ExperimentalMemCheck"
	@echo "... Experimental"
	@echo "... NightlySubmit"
	@echo "... ExperimentalSubmit"
	@echo "... ContinuousStart"
	@echo "... ContinuousUpdate"
	@echo "... hugetest"
	@echo "... realloc_test"
	@echo "... leaktest"
	@echo "... gctest"
	@echo "... middletest"
	@echo "... smashtest"
	@echo "... DISTlib"
	@echo "... ptc"
	@echo "... madx"
	@echo "... madxbin"
	@echo "... ndiff"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

